### ISSUE TITLE
Angular 1.2.3 breaks multi tags

### ISSUE THREAD

**Issue by lnu** [angular-ui/ui-select2#121]
Hello,

since upgrading to angular 1.2.3 I always get a javascript error when using multi tags.
You can check with this plunk:http://run.plnkr.co/plunks/oFYw3fz9jbGnn7isfN37/

If you choose an item you'll see errors added to the console.

It's due to this angular commit:https://github.com/angular/angular.js/commit/a090400f09d7993d102f527609879cdc74abae60

Any ideas on how to fix it?

edit: my mistake, it's related to issue https://github.com/angular-ui/ui-select2/pull/116

**Comment by Danita** [comment]
+1 I'm having about the same problem, but without javascript errors.

**Comment by BaconSoap** [comment]
Does it still break for you with the newest version from this repo?

**Comment by lnu** [comment]
I updated the plunkr with the latest version and it works without errors.
Meanwhile I used the fix proposed here https://github.com/angular/angular.js/issues/5219#issuecomment-29739353

**Comment by BaconSoap** [comment]
Thanks for the link, I'm working back through older issues to try and clear them out. I'll look into that solution; it looks safe and like it would be a final fix for these related problems, but I want to make sure.

**Comment by Danita** [comment]
@BaconSoap Using  `angular-ui-select2#~0.0.5` I'm no longer having problems, but I had to use the workaround mentioned by @lnu. If I use `<input>` instead of `<div>` I get this error:

```
TypeError: Cannot use 'in' operator to search for '0' in 1
    at isArraylike (bower_components/jquery/jquery.js:862:65)
    at Function.jQuery.extend.map (bower_components/jquery/jquery.js:680:14)
    at clazz.data (bower_components/select2/select2.js:3112:25)
    at HTMLInputElement.<anonymous> (bower_components/select2/select2.js:3167:45)
    at Function.jQuery.extend.each (bower_components/jquery/jquery.js:590:23)
    at jQuery.fn.jQuery.each (bower_components/jquery/jquery.js:237:17)
    at $.fn.select2 (bower_components/select2/select2.js:3134:14)
    at controller.$render (bower_components/angular-ui-select2/src/select2.js:99:21)
    at Object.fn (bower_components/angular-ui-select2/src/select2.js:92:24)
    at Scope.$digest (bower_components/angular/angular.js:11581:29) 

```

**Comment by run26kimo** [comment]
+1
