### ISSUE TITLE
Error With MEAN.JS

### ISSUE THREAD

**Issue by djindjic** [angular-ui/ui-select2#275]
just default setting and first select sample from documentation throw this error:
TypeError: undefined is not a function
    at Object.compile (http://localhost:3000/lib/angular-ui-select2/src/select2.js:20:25)
    at applyDirectivesToNode (http://localhost:3000/lib/angular/angular.js:6466:32)
    at compileNodes (http://localhost:3000/lib/angular/angular.js:6036:15)
    at compileNodes (http://localhost:3000/lib/angular/angular.js:6048:15)
    at compileNodes (http://localhost:3000/lib/angular/angular.js:6048:15)
    at compileNodes (http://localhost:3000/lib/angular/angular.js:6048:15)
    at compile (http://localhost:3000/lib/angular/angular.js:5969:15)
    at http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:3324:20
    at nodeLinkFn (http://localhost:3000/lib/angular/angular.js:6704:13)
    at compositeLinkFn (http://localhost:3000/lib/angular/angular.js:6098:13) <select ui-select2="{ allowClear: true}" ng-model="select2" data-placeholder="Pick a number"> 

I have no idea what's wrong I'm doing...
everything is installed as well and all references are included right

**Comment by Freyskeyd** [comment]
I have the same error but i don't use MEAN.js.
I think it's a DOM error:

```
repeatOption = tElem.find('option[ng-repeat], option[data-ng-repeat]');
```

**Comment by bhaveshvavdiya** [comment]
I was also getting same error. But, I have found the solution for that.
You need to required insert script files in sequence.
You can find sequance below :

jquery/dist/jquery.js
select2/select2.js
/\* Start adding all angular js _/
angular.js
...
...
/_ End adding all angular js */
angular-ui-select2/src/select2.js

**Comment by PowerKiKi** [comment]
Thanks for the solution
