### ISSUE TITLE
Error on search

### ISSUE THREAD

**Issue by paulomcnally** [angular-ui/ui-select2#283]
```
 TypeError: undefined is not a function
    at http://localhost:9000/js/services/select.js:1247:105
    at http://localhost:9000/js/angular.min.js:193:49
    at http://localhost:9000/js/angular.min.js:108:398
    at Object.<anonymous> (http://localhost:9000/js/angular.min.js:107:271)
    at k.$digest (http://localhost:9000/js/angular.min.js:122:233)
    at k.$apply (http://localhost:9000/js/angular.min.js:125:307)
    at $$debounceViewValueCommit (http://localhost:9000/js/angular.min.js:218:345)
    at $setViewValue (http://localhost:9000/js/angular.min.js:218:73)
    at HTMLInputElement.m (http://localhost:9000/js/angular.min.js:153:199)
    at HTMLInputElement.m.event.dispatch (http://localhost:9000/js/jquery.js:3:8436)
```

**Comment by PowerKiKi** [comment]
ui-select2 is deprecated, use https://github.com/angular-ui/ui-select instead
